apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test-api-key-4
  janus-idp.io/tekton: test-api-key-4
  backstage.io/kubernetes-id: test-api-key-4
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-api-key-4
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
